[package]
name = "bevy_egui"
version = "0.4.2"
authors = ["mvlabat <mvlabat@gmail.com>"]
description = "A plugin for Egui integration into Bevy"
license = "MIT"
edition = "2018"
repository = "https://github.com/mvlabat/bevy_egui"
exclude = ["assets/**/*", ".github/**/*"]
resolver = "2"

[package.metadata.docs.rs]
no-default-features = true # clipboard crate fails the build currently https://github.com/rust-lang/docs.rs/issues/695

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["manage_clipboard", "open_url"]
manage_clipboard = ["clipboard", "thread_local"]
open_url = ["webbrowser"]

[dependencies]
bevy = { version = "0.5", default-features = false, features = ["render", "bevy_winit"] }
#use dynamic for  Fast Compile dependencies required , https://bevyengine.org/learn/book/getting-started/setup/
#bevy = { version = "0.5", default-features = false, features = ["bevy_wgpu", "x11", "png", "dynamic"] }
egui = "0.11.0"
webbrowser = { version = "0.5.5", optional = true }
winit = { version = "0.24.0", features = ["x11"], default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clipboard = { version = "0.5.0", optional = true }
thread_local = { version = "1.1.0", optional = true }

[dev-dependencies]
version-sync = "0.9.2"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
bevy = { version = "0.5", default-features = false, features = ["bevy_wgpu", "x11", "png"] }
#use dynamic for  Fast Compile dependencies required , https://bevyengine.org/learn/book/getting-started/setup/
#bevy = { version = "0.5", default-features = false, features = ["bevy_wgpu", "x11", "png", "dynamic"] }

[[example]]
name = "simple"
path = "examples/simple.rs"

[[example]]
name = "two_window"
path = "examples/two_windows.rs"


[[example]]
name = "ui"
path = "examples/ui.rs"

[[example]]
name = "bevy_central_panel"
path = "examples/bevy_central_panel.rs"


